AL-4757 when listLeafFiles, add  ScanSubDir Enable setting
Kyligence/spark pull request #566
Opened 2022-11-22 12:25 UTC by jlfsdtc

### What changes were proposed in this pull request?

### Why are the changes needed?

### Does this PR introduce _any_ user-facing change?

### How was this patch tested?

2022-11-23 09:30 UTC, yugan91sh requested changes

2022-11-23 09:30 UTC, yugan91sh commented on sql/core/src/main/scala/org/apache/spark/sql/execution/datasources/InMemoryFileIndex.scala
> +      val (files, discovered) = listLeafFilesScanSubDirEnable(rootPaths)
private def refresh0(): Unit = {
    val files = listLeafFiles(rootPaths)
    cachedLeafFiles =
      new mutable.LinkedHashMap[Path, FileStatus]() ++= files.map(f => f.getPath -> f)
    cachedLeafDirToChildrenFiles = if (sparkSession.sessionState.conf.recursiveFileLookup) {
      recursiveDirChildrenFiles(files)
    } else {
      files.toArray.groupBy(_.getPath.getParent)
    }
    cachedPartitionSpec = null
  }

  private def recursiveDirChildrenFiles(files: mutable.LinkedHashSet[FileStatus])
  : Map[Path, Array[FileStatus]] = {
    val rootPathSet = rootPaths.toSet
    val reorganized = mutable.LinkedHashMap[Path, mutable.LinkedHashSet[FileStatus]]()
    files.foreach { f => // f is a file, not a directory.
      var parent = f.getPath.getParent
      while(parent != null && !rootPathSet.contains(parent)) {
        reorganized.getOrElseUpdate(parent, mutable.LinkedHashSet[FileStatus]()).add(f)
        parent = parent.getParent
      }
    }
    reorganized.mapValues(_.toArray).toMap
  }

2022-11-23 09:46 UTC, yugan91sh commented on sql/core/src/main/scala/org/apache/spark/sql/execution/datasources/InMemoryFileIndex.scala
> +      val (files, discovered) = listLeafFilesScanSubDirEnable(rootPaths)
root path:
/user/hive/ssb.db/lineorders/


/user/hive/ssb.db/lineorders/part1=202210/a1.parquet
/user/hive/ssb.db/lineorders/part1=202210/a2.parquet
/user/hive/ssb.db/lineorders/part1=202210/tez1/b1.parquet
/user/hive/ssb.db/lineorders/part1=202210/tez1/b2.parquet
/user/hive/ssb.db/lineorders/part1=202210/z1.parquet

before change:

/user/hive/ssb.db/lineorders/part1=202210/ -> a1.parquet,a2.parquet,z1.parquet
/user/hive/ssb.db/lineorders/part1=202210/tez1/ -> b1.parquet,b2.parquet

after change:

/user/hive/ssb.db/lineorders/part1=202210/ -> a1.parquet,a2.parquet,b1.parquet,b2.parquet,z1.parquet
/user/hive/ssb.db/lineorders/part1=202210/tez1/ -> b1.parquet,b2.parquet

-----


/user/hive/ssb.db/lineorders/part1=202211/tez1/b1.parquet
/user/hive/ssb.db/lineorders/part1=202211/tez1/b2.parquet

before change:
/user/hive/ssb.db/lineorders/part1=202211/tez1/ -> b1.parquet,b2.parquet

after change:
/user/hive/ssb.db/lineorders/part1=202211/ -> b1.parquet,b2.parquet
/user/hive/ssb.db/lineorders/part1=202211/tez1/ -> b1.parquet,b2.parquet

----

2022-11-23 10:33 UTC, yugan91sh requested changes

2022-11-23 10:33 UTC, yugan91sh commented on sql/catalyst/src/main/scala/org/apache/spark/sql/internal/SQLConf.scala
> +      .doc("If true, Spark will not fetch the block locations for each file on " +
这个说明和配置对不上吧，是 spark.sql.sources.ignoreDataLocality 的说明

2022-11-23 10:34 UTC, jlfsdtc commented on sql/catalyst/src/main/scala/org/apache/spark/sql/internal/SQLConf.scala
> +      .doc("If true, Spark will not fetch the block locations for each file on " +
这个还没改, 还在测试功能

2022-11-25 01:40 UTC, jlfsdtc commented
<img width="574" alt="image" src="https://user-images.githubusercontent.com/29626183/203883495-68deb1f1-4c26-4a2e-8007-b4d869457950.png">

2022-11-25 02:39 UTC, zheniantoushipashi approved these changes

2022-11-25 02:50 UTC, yugan91sh approved these changes

2022-11-25 02:50 UTC, merged