KE-40636 Fix spark history server leaves inprogress files forever
Kyligence/spark pull request #601
Opened 2023-03-14 09:12 UTC by sibingzhang

### What changes were proposed in this pull request?

### Why are the changes needed?

### Does this PR introduce _any_ user-facing change?

### How was this patch tested?

2023-03-14 09:18 UTC, yugan95 requested changes

2023-03-14 09:18 UTC, yugan95 commented on core/src/main/scala/org/apache/spark/deploy/history/FsHistoryProvider.scala
> +    def shouldDelete(fileStatus: FileStatus): Boolean = {
如果是 current active application，don't remove

2023-03-14 10:15 UTC, yugan95 submitted a review, later dismissed

2023-03-17 01:47 UTC, sibingzhang commented
<img width="1877" alt="image" src="https://user-images.githubusercontent.com/74443791/225791196-b7a8bd04-5731-4993-a526-83f36c6b3849.png">

2023-03-17 02:30 UTC, yugan95 requested changes

2023-03-17 02:30 UTC, yugan95 commented on core/src/test/scala/org/apache/spark/deploy/history/FsHistoryProviderSuite.scala
> -    validLogCount += 1
不要删这行代码，把它注掉并解释原因

2023-03-17 06:33 UTC, sibingzhang commented on core/src/test/scala/org/apache/spark/deploy/history/FsHistoryProviderSuite.scala
> -    validLogCount += 1
done

2023-03-17 06:44 UTC, yugan95 approved these changes

2023-03-17 07:16 UTC, merged