AL-8998 Fix resizing for ArrayBuffer in scala-2.12
Kyligence/spark pull request #691
Opened 2023-10-17 09:25 UTC by Mrhs121

### What changes were proposed in this pull request?

### Why are the changes needed?

### Does this PR introduce _any_ user-facing change?

### How was this patch tested?

2023-10-17 10:49 UTC, Mrhs121 commented
retest this please

2023-10-18 03:09 UTC, yugan95 requested changes

2023-10-18 03:09 UTC, yugan95 commented on sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/expressions/ExpressionSet.scala
> +    private val originals: mutable.Buffer[Expression] = new BigArrayBuffer)
`-- =` 最终会走到 `BigArrayBuffer#remove` 方法，请仔细确认一下这个方法是否需要做调整，对比 scala 社区的实现

2023-10-18 03:29 UTC, Mrhs121 commented on sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/expressions/ExpressionSet.scala
> +    private val originals: mutable.Buffer[Expression] = new BigArrayBuffer)
2.12 和 2.13 的实现逻辑上没有区别，2.13 在remove这里稍微优化了一点代码效率

2023-10-18 04:24 UTC, Mrhs121 commented
retest this please

2023-10-18 05:35 UTC, Mrhs121 commented
retest this please

2023-10-18 06:03 UTC, yugan95 submitted a review, later dismissed
LGTM

2023-10-18 07:47 UTC, Mrhs121 commented
retest this please

2023-10-18 08:47 UTC, Mrhs121 commented
retest this please

2023-10-18 09:48 UTC, Mrhs121 commented
retest this please

2023-10-18 11:10 UTC, Mrhs121 commented
retest this please

2023-10-18 14:47 UTC, Mrhs121 commented
retest this please

2023-10-19 04:48 UTC, Mrhs121 commented
retest this please

2023-10-19 08:43 UTC, Mrhs121 commented
retest this please

2023-10-20 01:37 UTC, Mrhs121 commented
retest this please

2023-10-20 08:23 UTC, zheniantoushipashi approved these changes

2023-10-20 08:30 UTC, merged